version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    command: /nsqd --broadcast-address 127.0.0.1 --lookupd-tcp-address=nsqlookup:4160 

  # nsqadmin:
  #   image: nsqio/nsq
  #   hostname: nsqadmin
  #   links:
  #     - nsqlookup:nsqlookup
  #   ports:
  #     - "4171:4171"
  #   command: /nsqadmin --lookupd-http-address=nsqlookup:4161
